### ISSUE TITLE
There is change on repository for installing the external-dns

### ISSUE THREAD

**Issue by Nadeem-Mansuri** [stacksimplify/terraform-on-aws-eks#9]
There is a change on the repository for installing the external-DNS from k8s.gcr.io/external-dns/external-dns to registry.k8s.io/external-dns/external-dns. 
I request you to please review and modify your repository accordingly.

FROM

  set {
    name = "image.repository"
    value = "k8s.gcr.io/external-dns/external-dns" 
  }    

TO
  set {
    name = "image.repository"
    value = "registry.k8s.io/external-dns/external-dns"  
  }

**Comment by stacksimplify** [comment]
Hi Nadeem,
I have updated the external dns install yaml file with new image repo
Thank you for letting me know

Regards,
Kalyan Reddy Daida
